runtime: nodejs16
service: default

env_variables:
  SQL_USER: ${PROD_DATABASE_USER}
  SQL_PASSWORD: ${PROD_DATABASE_PASS}
  SQL_DATABASE: ${PROD_DATABASE_NAME}
  INSTANCE_CONNECTION_NAME: ${PROD_DATABASE_HOST}