# App Engine Deployment
# steps:
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'bash'
#   args: ['-c', 'gcloud app deploy']
# timeout: '1600s'

# Cloud Run Deployment
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/campus-818f1/campus-backend', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/campus-818f1/campus-backend']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'production'
    - '--image'
    - 'gcr.io/$PROJECT_ID/campus-backend:$COMMIT_SHA'
    - '--region'
    - 'asia-southeast2'
    - '--add-cloudsql-instances'
    - 'campus-818f1:asia-southeast2:campus-backend'
    - '--set-env-vars'
    - 'INSTANCE_UNIX_SOCKET="/cloudsql/campus-818f1:asia-southeast2:campus-backend"'
    - '--set-env-vars'
    - 'INSTANCE_CONNECTION_NAME="campus-818f1:asia-southeast2:campus-backend"'
    - '--set-env-vars'
    - 'DB_NAME="campus"'
    - '--set-env-vars'
    - 'DB_USER="root"'
    - '--set-env-vars'
    - 'DB_PASS="root"'
  images:
  - 'gcr.io/$PROJECT_ID/campus-backend:$COMMIT_SHA'