# App Engine Deployment
# steps:
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'bash'
#   args: ['-c', 'gcloud app deploy']
# timeout: '1600s'

# Cloud Run Deployment
steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/campus-818f1/campus-backend", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/campus-818f1/campus-backend"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        gcloud run deploy production --image gcr.io/campus-818f1/campus-backend \
        --add-cloudsql-instances $$PROD_DATABASE_HOST \
        --set-env-vars INSTANCE_UNIX_SOCKET="/cloudsql/$$PROD_DATABASE_HOST" \
        --set-env-vars INSTANCE_CONNECTION_NAME=$$PROD_DATABASE_HOST \
        --set-env-vars DB_NAME=$$PROD_DATABASE_NAME \
        --set-env-vars DB_USER=$$PROD_DATABASE_USER \
        --set-env-vars DB_PASS=$$PROD_DATABASE_PASS \
        --region asia-southeast2 \
        --allow-unauthenticated
