# App Engine Deployment
# steps:
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'bash'
#   args: ['-c', 'gcloud app deploy']
# timeout: '1600s'

# Cloud Run Deployment
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/campus-818f1/campus-backend', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/campus-818f1/campus-backend']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
 args:
   - 'run'
   - 'deploy'
   - 'campus-backend'
   - '--image'
   - 'gcr.io/$PROJECT_ID/campus-backend:$COMMIT_SHA'
   - '--region'
   - 'asia-southeast2'
 images:
 - 'gcr.io/$PROJECT_ID/campus-backend:$COMMIT_SHA'