steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_DOCKER_IMAGE}", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_DOCKER_IMAGE}"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        gcloud run deploy production --image ${_DOCKER_IMAGE} \
        --add-cloudsql-instances ${_INSTANCE_CONNECTION_NAME} \
        --set-env-vars INSTANCE_UNIX_SOCKET="/cloudsql/${_INSTANCE_CONNECTION_NAME}" \
        --set-env-vars INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME} \
        --set-env-vars DB_NAME=${_DB_NAME} \
        --set-env-vars DB_USER=${_DB_USER} \
        --set-env-vars DB_PASS=${_DB_PASS} \
        --region asia-southeast2 \
        --allow-unauthenticated
