steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/campus-818f1/campus-backend:$COMMIT_SHA', '-t', 'gcr.io/campus-818f1/campus-backend:latest', '.']
images:
- 'gcr.io/campus-818f1/campus-backend:latest'
- 'gcr.io/campus-818f1/campus-backend:$COMMIT_SHA'

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '-t', 'gcr.io/campus-818f1/campus-backend:$COMMIT_SHA', '-t', 'gcr.io/campus-818f1/campus-backend:latest', '.']
images:
- 'gcr.io/campus-818f1/campus-backend:latest'
- 'gcr.io/$PROJECT_ID/campus-backend:$COMMIT_SHA'

steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud app deploy']
timeout: '1600s'